name: b
on:
  push:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo '{"dependencies":{"mineflayer":"latest","bedrock-protocol":"latest"},"scripts":{"start":"node index.js"}}' > package.json
          echo "const mineflayer = require('mineflayer');
          const bot = mineflayer.createBot({
              host: 'Youtube-ng80.aternos.me',
              port: 26773,
              username: 'bot',
              version: false
          });
          bot.on('spawn', () => console.log('OK'));
          bot.on('error', (err) => console.log('Error:', err.message));" > index.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm i
      - run: timeout 1000 npm start || exit 0
